name: Continuos Deployment (Prod)

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Project Image 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: parth3083/gitops-practice:${{github.sha}}

      - name: Cloning the repos and update the image and push tags
        env:
          PAT: ${{secrets.PAT}}
        run: |
          git clone https://github.com/parth3083/gitops-argocd.git

          cd gitops-argocd

          sed -i 's|image: nginx|image: parth3083/gitops-practice:${{github.sha}}|' manifest.yml

          git config user.name "Github Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Updated the image of the project to tag ${{github.sha}}"
          git push https://${PAT}@github.com/parth3083/gitops-argocd main


